title: Personal Projects and Research – [Your Full Name]
description: A curated portfolio of software development projects, technical experiments, and research contributions by [Your Full Name].
theme: jekyll-theme-minimal
